stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - train
    outs:
    - dataset_dogs_and_cats
  train:
    cmd: python src/train.py
    deps:
    - dataset_dogs_and_cats
    - src/train.py
    params:
    - train
    outs:
    - history.pkl
    - model.h5
    - pretrained_weights.h5
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - history.pkl
    - model.h5
    - src/evaluate.py
    metrics:
    - score.json:
        cache: false
    plots:
    - plot.json:
        cache: false
